{% set name = "backoff" %}
{% set version = "1.7.0" %}
{% set sha256 = "b3a19ad74302fd8e8307239526b57bb338183ac690912d3fcdaa9f8ecff83a3d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backoff

about:
  home: https://github.com/litl/backoff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Function decoration for backoff and retry'
  description: |
    This module provides function decorators which can be used to wrap a function such that it will be retried until
    some condition is met. It is meant to be of use when accessing unreliable resources with the potential for
    intermittent failures i.e. network resources and external APIs. Somewhat more generally, it may also be of use for
    dynamically polling resources for externally generated content.
  dev_url: https://github.com/litl/backoff

extra:
  recipe-maintainers:
    - gatesn
    - bgreen-litl
