travis:
  secure:
    BINSTAR_TOKEN: X9M+Djj6uFqV43CzQaYhzc9c8f9T2ID+ZZYMmP9iUNHoKhzNpF90fpg+leOcFVAuepYXQpKvB/NMOFmueVhxyDJm2xE0Vo1aS3EtSGZ3+WpkQyYw+1H+I0n4Sq3lMg84s0sku50K9TRKUUliEUZXvyIDx1MF2zHS3LlLTtbv2FfAK1lXudcJzDvEovG2e0Q5bRdtpfA3cb+GHbRir+MpSV8XtgqE1CBYlcbwOMnOBDTmNPBO6eVtGwGrpv8b8oS0QHfsQC11k3rJM/N6q/PRBO1w6zRwW9/09BZZ8tM8y2TeVkUlE//x5pWW5LIxrdmyEGIeVyRoATMkMn/GJpgr0rdlFbwJDZF5HN8XpE+bATXAAuWLuoW0fbcGCWp4ZGPwpidnxinZyS2o+vvJrXjKcwCS3iX79c/akqQbuy8U82G7moJ1Cb7zsSnw9lYxBLrDye6h9wl8zmpX+ILVnNO3JDFBcHhAg1ktRpxnYMeR8KEXJJX438nVXs1IV2LqtCnT7/XRi5sZEHabhmiBjydjEF0XG5y/pZfgeZfS4dOo8lzR9nzJplMpFpiTvpkU+qfI5tHqMwbnPE80VHhZoV1cCZi1aXfyd/WknWIxKAbnhc7AMh8GkspYmNDwzbL+BhrU3liIGvDLTekhBMJsx7T8YrvapAs5hCPVCyIMmoZm9Cc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
