travis:
  secure:
    BINSTAR_TOKEN: nKTTmUtj5iNHmeLJqJGuUQFR8tR41GIK0I1VeL1NIBOcSKd2mvlaG7zIrzINY1CSm6C3+0UgXHCqwfD2SrVK2JDmspn4ABSEUOmnvgIzNWWSmpDJMxhPInHiBuGsGOpKnjsVoTd64Bs30fV6R2tYEeqvz2YTECjtIkHLR95wKF7Pojh5xG+U/EAWPEo1CTEpibaT4tEpDugza8IFKkpyXm96JqRuct1KHC4fcDb6YeNdBi/R9oOPAHtnFbgt2TfD2yJvZjvfWIl1UwEavZEnk1exSf2TvOpykphWxyZlcgaSbFJTGfYCnvTLZojXrIboMWvFJouVBsIHkkgSSExhB9s6zK8KSib/gkBi0bedEpO7tl4EK2OvlRTjbfuC5SReqat30ej7XHq3lDKyDhct9TyD1db5eEFNqjr6iwEDooJpMzrBNfSu69fASkUHPi17mGsU2iC3CqE7AkhU4B5tJxZ/QdRNjKusVZ/esXu6qswPtddi4BKjIAicA14lzDTtH5D6J+UCL3hh3HVL6dmf/Sf4ZaJyxCgdKWZbbwN4g5b1eM9Iu2LU2MujhQE892OnazjOPsAsMEo2jbHh2djy2L+6p9H5FMYnzY8aEF7+zY9eyJNJ5MvYTseaBTr2eNo09RageAZL/XO999IvXcke0eH/JxT3LUyMyf+LcC1zlto=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
