travis:
  secure:
    BINSTAR_TOKEN: qwT6MSbC5bQZxEIMgzQCKaZmCG2flVV5zAIe0HGbg6+NhsXFgr2yryh8lNl9n7Q/R61NzN9l6CHOVgHlHUgSHOq3SlwbqITx+KGcCuzxhrOoGYCEtCFLJIGu6PRe9mJCb+qsd6alv8GGydbbcSwmiSOax08cxFbx81ykLxt0Ka3p/OzarsZnWUWBWZwA7wugiULbDumq9Ty/6Cz5bjjnmXOktanLBfKZC3tyJiymfS9a4E7kYpQW8xl+cn5dRqYfurSoNQXamQhpdoqz39UcSMMSIN+Sem3W46KbJVcsevhaFiSLxvd8NF/v0xMk1bXIDe/NJuu6PNAbgVp1U9B1fCo+kKdKdQowSIHkERGuwbgrq1n2eSf+bth4kfMwHCwYS13cktiUg8XNThlBuE1lspYL2DOZWnuZF5KYPRSoEbGkXe3Zyg5yi4Ht7PB6DQCJoFeZ4dsRwmIjEkmYQe6YanwAY23TIUXym8Uk+vT5SEaO0AoZeJHBiHWeyXojBQKPkXzsr7eaYNp8RDKuxZApGAvtGyUjZtVs+U12bvKmov9GC3ongtKdcBPUsKcmmJS2/Pxto+aybqcnigW5nMXhhfA3L6rfYJ60Io44sU8ZaaFWJDbgZuQA1kawItHo/OuFNEx0XBCgjOZsdLd2BfBU/IHSbR2TKBNsERUV8mF7+us=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
