travis:
  secure:
    BINSTAR_TOKEN: cTQL65UGVyRR8QJMRNT8SOh4uyqXVqacFoH60BaM0wXDKt6uWxx6CKu7JWKuaFzol2tMb5PBWilFYqFuSvELVuxkeZ38YjH/5VY18zZefZ8YZxtYABuzy8lSBUGcj5UTvjb1drhjRv5P/XUrOckNAyYasegqZ4+h7wtBdW5fu0/iVeUJtdAFqb2hfP0C497KGb7m0eAG+x8Kaq0IR7P3VI05aDvw1CbPcUvI/4AnLty4pyMHJgE4L3XrXMUKHm3Oi6KNuoEUfr6r90I9evaVC+cGgqJEYWLfWan+xgyewsYombbQJWk3VYdVJfCG2OyKBhc5m2YQ0JgU7vaA1Y/4wQBCPfY1ooiPStyOgygP9V515bgm7Mb8dny3U27yKpuDqsvM9Ust1NG0B444HyWtJg7Idb4A8fi99sTqpWHC1E/UGzZ38vmgi2eaku+dRuhgLOvWrdgCYoepv/V7fcOPZadMNMcf5q+2vK37XyAp/Gf78xkA8UXQDnqxabpmCX6oUGhe7IXjioRaW1avj4iR4Yf33j8aRT8XAlF6okZ4MfiB+HN/dvKPwKMWf8GUvewjeFtrfMW5nHGjQC/5du12/PHA3gNmkyo9bWPNVT5WZONpUmobeWgSKY8qfjKUlWLe0+lY1t84AYXstvo1KRyzi0NjE7k1POBuu8dDLRM5W5g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
